---
version: 2

project_name: komodo-secrets-sync

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    main: cmd/main.go
    env:
      - CGO_ENABLED=1
      # Using zig or specific cross-compilers is often needed for CGO cross-compiling
      - CC={{ if eq .Os "linux" }}musl-gcc{{ else }}clang{{ end }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/veerendra2/gopackages/version.Version={{.Version}}
      - -X github.com/veerendra2/gopackages/version.Revision={{.Commit}}
      - -X github.com/veerendra2/gopackages/version.Branch={{.Branch}}
      - -X github.com/veerendra2/gopackages/version.BuildUser={{.Env.USER}}
      - -X github.com/veerendra2/gopackages/version.BuildDate={{.Date}}
      # Added static linking flags from your Taskfile for Linux
      - '{{ if eq .Os "linux" }}-linkmode external -extldflags ''-static -Wl,-unresolved-symbols=ignore-all''{{ end }}'

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
