---
version: "3"
silent: true

vars:
  MAIN_FILE: cmd/main.go
  APP_NAME: komodo-secrets-sync
  GOPATH_BIN:
    sh: echo "$(go env GOPATH)/bin"
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  BUILD_TIME:
    sh: date '+%Y-%m-%d@%H:%M:%S'
  BUILD_USER:
    sh: id -un
  REVISION:
    sh: git rev-parse HEAD
  VERSION:
    sh: git describe --tags --always

env:
  GOBIN: "{{.GOPATH_BIN }}"
  CGO_ENABLED: 1
  CC:
    sh: |
      case "{{.OS}}" in
        linux) echo "musl-gcc" ;;
        darwin) echo "clang" ;;
        *) echo "" ;;
      esac
  CXX:
    sh: |
      case "{{.OS}}" in
        darwin) echo "clang++" ;;
        *) echo "" ;;
      esac

tasks:
  run:
    desc: "Runs the main application"
    deps:
      - vet
    cmds:
      - go run {{.MAIN_FILE}}
    env:
      LOG_FORMAT: console
      LOG_ADD_SOURCE: false
      LOG_LEVEL: info

  lint:
    desc: "Run static analysis and code linting using golangci-lint"
    deps:
      - install
    cmds:
      - golangci-lint run --timeout 3m

  fmt:
    desc: "Formats all Go source files"
    cmds:
      - go fmt ./...

  vet:
    desc: "Examines Go source code and reports suspicious constructs"
    cmds:
      - go vet ./...

  test:
    desc: "Runs all tests in the project"
    aliases:
      - tests
    deps:
      - vet
    cmds:
      - go test ./...

  build:
    desc: "Build the application binary for the current platform"
    deps:
      - vet
    cmd: |
      go build -ldflags "\
        -X github.com/veerendra2/gopackages/version.Version={{.VERSION}} \
        -X github.com/veerendra2/gopackages/version.Revision={{.REVISION}} \
        -X github.com/veerendra2/gopackages/version.Branch={{.BRANCH}} \
        -X github.com/veerendra2/gopackages/version.BuildUser={{.BUILD_USER}} \
        -X github.com/veerendra2/gopackages/version.BuildDate={{.BUILD_TIME}}" \
        -o dist/{{.APP_NAME}} {{.MAIN_FILE}}

  build-docker:
    desc: "Build Docker image"
    cmds:
      - docker build -t {{.APP_NAME}} .

  security:
    desc: "Run security vulnerability scan"
    deps:
      - install
    cmds:
      - govulncheck ./...

  install:
    desc: "Install required tools and dependencies"
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - test -f {{.GOPATH_BIN}}/govulncheck
      - test -f {{.GOPATH_BIN}}/golangci-lint

  all:
    desc: "Run comprehensive checks: format, lint, security and test"
    cmds:
      - task fmt
      - task lint
      - task vet
      - task security
      - task test
